version: '3'
services:
  microservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8000"
      - "443:443"
      - "9200:9200"
    restart: always
    tmpfs:
      - /tmp