version: '3'
services:
  mysql:
    image: mysql:5.7.8
    env_file:
      - .env
    networks:
      - projetB

  microservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8000"
      - "443:443"
      - "9200:9200"
    restart: always
    networks:
      - projetB
    tmpfs:
      - /tmp
    depends_on:
    - mysql

networks:
  projetB:
    external: true