---
version: '3'
services:
  mysql:
    image: mysql:5.7.8
    env_file:
      - .env
    networks:
      - projetB

  drupal:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "443:443"
      - "80:80"
    env_file:
      - .env
    networks:
      - projetB

networks:
  projetB:
    external: true