---
- name: Deploy Drupal
  hosts: DrupalMachine
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Start Docker Compose
      command: docker-compose up -d
      args:
        chdir: /home/ubuntu/drupal
